filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-production
repositories:
- name: dev
  url: https://chanmi910.github.io/helm-repo
releases:
- chart: dev/jx3-msa-01
  version: 0.0.1
  name: jx3-msa-01
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
