apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: chanmi910
    provider: https://github.com
    providerKind: github
    repositories:
    - name: jx3-spring-demo
      #scheduler: environment-review-required
    - name: jx3-spring-test
    - name: node-example
      #scheduler: environment-review-required
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
